apiVersion: v1
kind: Pod
metadata:
  name: article
  namespace: tenz
  labels:
    app: article
spec:
  containers:
  - name: art
    image: art
    imagePullPolicy: Never
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: artpod-secret
          key: passw
    - name: MYSQL_USERNAME
      valueFrom:
        secretKeyRef:
          name: artpod-secret
          key: user

    - name: MYSQL_DB_NAME
      valueFrom:
        configMapKeyRef:
          name: artpod-conf
          key: database
    - name: HOST
      valueFrom:
        configMapKeyRef:
          name: artpod-conf
          key: namepod
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: pvo
      mountPath: /app/result
  - name: nginx
    image: nginx:1.18.0
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvo
      mountPath: /usr/share/nginx/html

  volumes:
  - name: pvo
    hostPath:
      path: /opt/art

---

apiVersion: v1
kind: Service
metadata:
  name: arty
  labels:
    app: article
spec:
  selector:
    app: article
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
